[package]
name = "rscat"
version = "0.1.0"
edition = "2021"
about = "A rust cat(1) clone"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
